### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [ ]:
# np.array -> vector
import numpy as np

a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# 2D -> Metrix
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3D -> Tensor
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
# dtype
np.array([1,2,0],dtype=bool)

array([ True,  True, False])

In [17]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [27]:
# with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [28]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
# np.random
np.random.random((3,4))

array([[0.83824051, 0.57477835, 0.62362588, 0.17900024],
       [0.41415952, 0.5109048 , 0.15147958, 0.47716889],
       [0.44097003, 0.3394447 , 0.03724757, 0.56612527]])

In [31]:
# np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [32]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [34]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [36]:
# ndim
a2.ndim

2

In [38]:
# shape
a2.shape

(3, 4)

In [40]:
# size
a2.size

12

In [44]:
# itemsize
a1.itemsize

8

In [46]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


In [47]:
# nbytes
a1.nbytes

80

In [49]:
# T(Transpose)
a2.T

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [52]:
# reshape()
a2.reshape(3,4)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [54]:
# flatten()
a2.flatten()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [55]:
# ravel()
a2.ravel()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

### Changing Datatype

In [58]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [59]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [60]:
# scalar operations

# arithmatic
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [62]:
# relational
a2 > 18

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [63]:
# vector operations

# arithmetic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

### Array Functions

In [67]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[43., 56., 63.],
       [74., 85., 86.],
       [ 5.,  8., 36.]])

In [71]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.max(a1)
np.min(a1,axis=1)
np.sum(a1)
np.prod(a1)

np.float64(118170376934400.0)

In [72]:
# mean/median/std/var
np.mean(a1)
np.median(a1)
np.std(a1)
np.var(a1)

np.float64(814.6666666666667)

In [73]:
# trigonomoetric functions
np.sin(a1)

array([[-0.83177474, -0.521551  ,  0.1673557 ],
       [-0.98514626, -0.17607562, -0.92345845],
       [-0.95892427,  0.98935825, -0.99177885]])

In [75]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [76]:
# log and exponents
np.log(a1)

array([[3.76120012, 4.02535169, 4.14313473],
       [4.30406509, 4.44265126, 4.4543473 ],
       [1.60943791, 2.07944154, 3.58351894]])

In [77]:
# round/floor/ceil
np.round(np.random.random((2,3))*100)

array([[29.,  3.,  7.],
       [53., 15., 59.]])

### Indexing and Slicing

In [78]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [79]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
a1[0]

np.int64(0)

In [82]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
a2[1,2]

np.int64(6)

In [84]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [85]:
a3[1,0,1]

np.int64(5)

In [86]:
a3[0,1,0]

np.int64(2)

In [87]:
a3[0,0,0]

np.int64(0)

In [88]:
# slicing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
a1[2:5]

array([2, 3, 4])

In [90]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
a2[0,:]

array([0, 1, 2, 3])

In [92]:
a2[:,2]

array([ 2,  6, 10])

In [93]:
a2[1,1:]

array([5, 6, 7])

In [94]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [96]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [99]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [100]:
a2[1,::3]

array([4, 7])

In [101]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [104]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [105]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [108]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [109]:
a3[0,1,:]

array([3, 4, 5])

In [110]:
a3[1,:,1]

array([10, 13, 16])

In [111]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [112]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

In [116]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [117]:
a2

for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [118]:
a3

for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [119]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [120]:
# reshape

In [124]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [125]:
# ravel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Stacking

In [129]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [130]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [132]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [135]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [138]:
# Vertical splitting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [139]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]