In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# Define the vocabulary size
voc_size = 10000

In [6]:
# One Hot Representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[3612, 2450, 9616, 188],
 [3612, 2450, 9616, 4549],
 [3612, 230, 9616, 7656],
 [8182, 6698, 3870, 7421, 8324],
 [8182, 6698, 3870, 7421, 2452],
 [1498, 3612, 3013, 9616, 8625],
 [9909, 1879, 3181, 7421]]

In [9]:
# word embedding Representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3612 2450 9616  188]
 [   0    0    0    0 3612 2450 9616 4549]
 [   0    0    0    0 3612  230 9616 7656]
 [   0    0    0 8182 6698 3870 7421 8324]
 [   0    0    0 8182 6698 3870 7421 2452]
 [   0    0    0 1498 3612 3013 9616 8625]
 [   0    0    0    0 9909 1879 3181 7421]]


In [12]:
# Feature representation
dim = 10

In [13]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 197ms/step


array([[[ 0.02891279, -0.02838019, -0.04026099,  0.00907056,
         -0.01182582,  0.02670098, -0.0296551 ,  0.0201092 ,
          0.00988469,  0.03474616],
        [ 0.02891279, -0.02838019, -0.04026099,  0.00907056,
         -0.01182582,  0.02670098, -0.0296551 ,  0.0201092 ,
          0.00988469,  0.03474616],
        [ 0.02891279, -0.02838019, -0.04026099,  0.00907056,
         -0.01182582,  0.02670098, -0.0296551 ,  0.0201092 ,
          0.00988469,  0.03474616],
        [ 0.02891279, -0.02838019, -0.04026099,  0.00907056,
         -0.01182582,  0.02670098, -0.0296551 ,  0.0201092 ,
          0.00988469,  0.03474616],
        [ 0.0096485 , -0.04295691, -0.01405265,  0.00067018,
          0.00927868,  0.03316471,  0.00378873, -0.00955142,
         -0.04829203,  0.02159036],
        [ 0.02641349,  0.03182414, -0.02313304, -0.01102865,
         -0.00131299,  0.01449263,  0.01139344, -0.0013933 ,
          0.00585085,  0.03046942],
        [-0.01159446, -0.01742274,  0.0470478 , -0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 3612, 2450, 9616,  188])

In [18]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 40ms/step


array([[ 0.02891279, -0.02838019, -0.04026099,  0.00907056, -0.01182582,
         0.02670098, -0.0296551 ,  0.0201092 ,  0.00988469,  0.03474616],
       [ 0.02891279, -0.02838019, -0.04026099,  0.00907056, -0.01182582,
         0.02670098, -0.0296551 ,  0.0201092 ,  0.00988469,  0.03474616],
       [ 0.02891279, -0.02838019, -0.04026099,  0.00907056, -0.01182582,
         0.02670098, -0.0296551 ,  0.0201092 ,  0.00988469,  0.03474616],
       [ 0.02891279, -0.02838019, -0.04026099,  0.00907056, -0.01182582,
         0.02670098, -0.0296551 ,  0.0201092 ,  0.00988469,  0.03474616],
       [ 0.0096485 , -0.04295691, -0.01405265,  0.00067018,  0.00927868,
         0.03316471,  0.00378873, -0.00955142, -0.04829203,  0.02159036],
       [ 0.02641349,  0.03182414, -0.02313304, -0.01102865, -0.00131299,
         0.01449263,  0.01139344, -0.0013933 ,  0.00585085,  0.03046942],
       [-0.01159446, -0.01742274,  0.0470478 , -0.03749895,  0.02514361,
        -0.01322495, -0.01778662,  0.03049499